"""Add tags column

Revision ID: 827ec3a33aef
Revises: 5828c7470c7a
Create Date: 2026-07-30 11:15:26.159983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '827ec3a33aef'
down_revision: Union[str, Sequence[str], None] = '5828c7470c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column("tags",
        sa.String(),
        nullable=False,
        server_default=""))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'tags')
    # ### end Alembic commands ###
